### PR TITLE
Feature/grid

### PR DESCRIPTION
**Pull request by dstuessy**
Alright, this is ready for review. Need to add Damien to github.

### CODE REVIEW

**Comment by dstuessy** [comment]
Added @NeilHiggins to review galen tests for grid, found in `~/test/visual/spec/grid.gspec`. The suite that gets executed for browserstack is `~/test/visual/browserstack.test`. Would probably be best to go through this together tomorrow as I need to get some other things done by the end of the day.

Added @Decad and @NathanRodger to review code.

@DamienEvans feel free to give this a look from home if you have the time!

**Review by nathanrodger — DISMISSED** [review]

**Review by NeilHiggins — COMMENTED** [review]
Visual tests have been QA'd.  Need to add checks to ensure gutters & margins are correct depending on device size.

**Comment by dstuessy** [comment]
@NeilHiggins @DamienEvans Added tests for grid gutter. Omitted the ones for the grid margins as they are much more difficult to test and less crucial to the layout.

**Comment by dstuessy** [comment]
@NeilHiggins Added the requested tests for the flushed grid

**Review by NeilHiggins — APPROVED** [review]

**Pull request merged**
