### PR TITLE
MINI-CONTACT - Committing lastest and updated code/markup after develo…

### PR DESCRIPTION
**Pull request by ambtlv**
…per review.

### CODE REVIEW

**Review by dstuessy — DISMISSED** [review]
Seems legit!

**Review by Decad — DISMISSED** [review]

**Comment by dstuessy** [comment]
@ambtlv @Decad not to be merged yet. Let's add some Galen tests!

**Comment by ambtlv** [comment]
@NeilHiggins - I have written Galen test for Mini Contact. Please review/run as you need. Cheers

**Review by NeilHiggins — APPROVED** [review]
The galen tests have been QA'd; They all look good as far as I'm concerned.

**Review by dstuessy — APPROVED** [review]

**Pull request merged**
